safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Kim Dae Woung"
description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"
baseurl: /
url: "https://eeppeeoo.github.io" # replace by your site's url
twitter_username: your-name
github_username:  lukas-h # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Kim Dae Woung"
address: "Taeanno, <br>Hwaseoung, Gyeonggi"
email: "nueyet@naver.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
